// Generated by update-puzzle-pics.sh - the puzzle's photo list.
window.CHONK_PUZZLE_IMAGES = [
  "puzzle-20260910-01.jpg",
  "puzzle-20260910-02.jpg",
  "puzzle-20260910-03.jpg",
  "puzzle-20260910-04.jpg",
  "puzzle-20260910-05.jpg",
  "puzzle-20260910-06.jpg",
  "puzzle-20260910-07.jpg",
  "puzzle-20260910-08.jpg",
  "puzzle-20260910-09.jpg",
  "puzzle-20260910-10.jpg",
  "puzzle-20260910-11.jpg",
];
