#!/bin/sh
# Update the Chonk Puzzle pictures with photos you have ALREADY cropped.
#
# Usage:
#   ./update-puzzle-pics.sh /path/to/cropped/photos
#
# What it does:
#   1. Moves the current puzzle photos (puzzle/*.jpg) into
#      archive/puzzle/YYYY-MM-DD/ so every past set stays browsable by date
#   2. Copies your new photos in as puzzle/puzzle-YYYYMMDD-NN.jpg,
#      downscaling anything larger than 880px (proportions untouched)
#   3. Rewrites puzzle/images.js with the new picture list
#
# Cropping is deliberately NOT automated: square-crop the photos yourself
# (or with KiroCrew) before running this. Non-square photos are accepted
# but warned about, since the board is square and will stretch them.
#
# Nothing is committed or pushed: review, then ./publish.sh.

set -eu

SRC="${1:?usage: ./update-puzzle-pics.sh /path/to/cropped/photos}"
cd "$(dirname "$0")"

if [ ! -d "$SRC" ]; then
  echo "Source folder not found: $SRC" >&2
  exit 1
fi

count=$(find "$SRC" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | wc -l | tr -d ' ')
if [ "$count" -eq 0 ]; then
  echo "No photos (jpg/jpeg/png) found in $SRC" >&2
  exit 1
fi
echo "$count new picture(s) in $SRC"

# 1. archive the current set
stamp=$(date +%Y-%m-%d)
have_jpgs=$(find puzzle -maxdepth 1 -name '*.jpg' | wc -l | tr -d ' ')
if [ "$have_jpgs" -gt 0 ]; then
  dest="archive/puzzle/$stamp"
  if [ -d "$dest" ]; then
    n=2
    while [ -d "archive/puzzle/$stamp-$n" ]; do n=$((n + 1)); done
    dest="archive/puzzle/$stamp-$n"
  fi
  mkdir -p "$dest"
  mv puzzle/*.jpg "$dest/"
  echo "Archived $have_jpgs puzzle picture(s) to $dest/"
else
  echo "No existing puzzle pictures to archive."
fi

# 2. install the new set (downscale to 880px max side, keep proportions)
day=$(date +%Y%m%d)
i=1
find "$SRC" -maxdepth 1 -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | sort | while IFS= read -r f; do
  name="puzzle-$day-$(printf '%02d' "$i").jpg"
  sips -s format jpeg -s formatOptions 85 --resampleHeightWidthMax 880 "$f" --out "puzzle/$name" >/dev/null 2>&1
  w=$(sips -g pixelWidth "puzzle/$name" | awk '/pixelWidth/ {print $2}')
  h=$(sips -g pixelHeight "puzzle/$name" | awk '/pixelHeight/ {print $2}')
  if [ "$w" -ne "$h" ]; then
    echo "  $name (${w}x${h}) WARNING: not square - the board will stretch it"
  else
    echo "  $name (${w}x${h})"
  fi
  i=$((i + 1))
done

# 3. rewrite puzzle/images.js
{
  echo "// Generated by update-puzzle-pics.sh - the puzzle's photo list."
  echo "window.CHONK_PUZZLE_IMAGES = ["
  for f in puzzle/puzzle-$day-*.jpg; do
    [ -e "$f" ] || continue
    echo "  \"$(basename "$f")\","
  done
  echo "];"
} > puzzle/images.js
echo ""
echo "puzzle/images.js updated:"
cat puzzle/images.js
echo ""
echo "Done. Review the pictures in puzzle/, then ./publish.sh to ship."
echo "Past sets live under archive/puzzle/ by date."
